#!/usr/bin/env node

/**
 * Generate app icons from the SVG icon
 * Generates: icon-192.png, icon-512.png, apple-touch-icon.png
 *
 * Usage: node scripts/generate-icons.js
 */

const fs = require("fs");
const path = require("path");

// Try to load sharp, with helpful error message if not available
let sharp;
try {
  sharp = require("sharp");
} catch (err) {
  console.error(
    "ERROR: 'sharp' package not found. Install it with:\n\n"
  );
  console.error("  npm install --save-dev sharp\n");
  console.error("or\n");
  console.error("  pnpm add -D sharp\n");
  process.exit(1);
}

const publicDir = path.join(__dirname, "../public");
const svgIconPath = path.join(publicDir, "icon.svg");

// Verify the SVG icon exists
if (!fs.existsSync(svgIconPath)) {
  console.error(`ERROR: Icon SVG not found at ${svgIconPath}`);
  process.exit(1);
}

const iconConfigs = [
  {
    name: "icon-192.png",
    size: 192,
    description: "PWA icon (192x192)",
  },
  {
    name: "icon-512.png",
    size: 512,
    description: "PWA icon (512x512)",
  },
  {
    name: "apple-touch-icon.png",
    size: 180,
    description: "Apple touch icon (180x180)",
  },
];

async function generateIcons() {
  console.log("Generating icons from SVG...\n");

  try {
    // Generate PNG icons from SVG
    for (const config of iconConfigs) {
      const outputPath = path.join(publicDir, config.name);
      console.log(`Generating ${config.description}...`);

      await sharp(svgIconPath)
        .resize(config.size, config.size)
        .png()
        .toFile(outputPath);

      const stats = fs.statSync(outputPath);
      console.log(`✓ Created ${config.name} (${stats.size} bytes)\n`);
    }

    console.log("All icons generated successfully!");
    console.log("\nGenerated files:");
    console.log("  - /public/icon-192.png");
    console.log("  - /public/icon-512.png");
    console.log("  - /public/apple-touch-icon.png");
    console.log("\nThe OG image is dynamically generated by the Next.js route.");
  } catch (error) {
    console.error("Error generating icons:", error.message);
    process.exit(1);
  }
}

generateIcons();
